apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: flask-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-demo-service
                port:
                  number: 80